dev_test_11

diff --git a/.github/workflows/sonarqube.yml b/.github/workflows/sonarqube.yml
--- a/.github/workflows/sonarqube.yml
+++ b/.github/workflows/sonarqube.yml
@@ -21,23 +21,35 @@ jobs:
         run: |
           sonar-scanner
           
-      - name: Check SonarQube Quality Gate
-        shell: cmd
+      - name: Get SonarQube Quality Gate
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # 令牌
           SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}  # 项目密钥
-          SONAR_HOST_URL: http://159.99.218.157:9002/
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         run: |
-          setlocal enabledelayedexpansion
-          for /f "tokens=*" %%i in ('curl -s -u %SONAR_TOKEN%: "%SONAR_HOST_URL%api/qualitygates/project_status?projectKey=%SONAR_PROJECT_KEY%"') do (
-              set "line=%%i"
-          )
-          echo Quality Gate status: !line!
-          echo !line! | findstr "OK" >nul
-          if errorlevel 1 (
-              echo Quality gate failed!
-              exit /b 1
-          )
+          cd C:\Work\projects\SonarQube\source\
+          python sonarqube_get_quality_gate_status.py "$SONAR_HOST_URL" "$SONAR_TOKEN" "$SONAR_PROJECT_KEY"
+          echo "quality_gate_status=$?" >> $GITHUB_ENV
+
+      - name: SonarQube Quality Gate
+        run: |
+          if [ "${{ env.quality_gate_status }}" -eq 0 ]; then
+            echo "SonarQube Quality Gate Passed!"
+          else
+            echo "SonarQube Quality Gate failed with exit code ${{ env.quality_gate_status }}"
+            exit 1
+          fi
+        # run: |
+        #   setlocal enabledelayedexpansion
+        #   for /f "tokens=*" %%i in ('curl -s -u %SONAR_TOKEN%: "%SONAR_HOST_URL%api/qualitygates/project_status?projectKey=%SONAR_PROJECT_KEY%"') do (
+        #       set "line=%%i"
+        #   )
+        #   echo Quality Gate status: !line!
+        #   echo !line! | findstr "OK" >nul
+        #   if errorlevel 1 (
+        #       echo Quality gate failed!
+        #       exit /b 1
+        #   )
       #- name: SonarQube Scan
       #  env:
       #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # 你可以在 GitHub Secrets 中存储 SonarQube 的token
