dev_test_28

diff --git a/.github/workflows/sonarqube.yml b/.github/workflows/sonarqube.yml
--- a/.github/workflows/sonarqube.yml
+++ b/.github/workflows/sonarqube.yml
@@ -29,14 +29,14 @@ jobs:
           host_url: http://159.99.218.157:9002
         run: |
           cd C:\Work\projects\SonarQube\source\
-          python sonarqube_get_quality_gate_status.py > result.txt
-          set /p result=<result.txt
-          if %ERRORLEVEL%==0 (
-            echo SonarQube Quality Gate Passed!. Result: %result%
-          ) else (
-            echo SonarQube Quality Gate failed with exit code: %ERRORLEVEL%.
-            exit /b %ERRORLEVEL%  # 退出工作流，状态为失败
-          )
+          python sonarqube_get_quality_gate_status.py
+          echo "result=$?" >> $GITHUB_ENV
+          if [ "${{ env.result }}" -eq 0]
+               echo "Script executed successfully."
+          else
+              echo "Script failed with return code: ${{ env.result }}"
+          fi
+
 
       # - name: SonarQube Quality Gate
       #   shell: cmd
@@ -44,6 +44,13 @@ jobs:
       #     echo "quality_gate_status=$?" >> $GITHUB_ENV
       #     if [ "${{ env.quality_gate_status }}" -eq 0 ]; then
       #       echo "SonarQube Quality Gate Passed!"
+              # set /p result=<result.txt
+          # if %ERRORLEVEL%==0 (
+          #   echo SonarQube Quality Gate Passed!. Result: %result%
+          # ) else (
+          #   echo SonarQube Quality Gate failed with exit code: %ERRORLEVEL%.
+          #   exit /b %ERRORLEVEL%  # 退出工作流，状态为失败
+          # )
       #     else
       #       echo "SonarQube Quality Gate failed with exit code ${{ env.quality_gate_status }}"
       #       exit 1
