dev_test_04

diff --git a/.github/workflows/sonarqube.yml b/.github/workflows/sonarqube.yml
--- a/.github/workflows/sonarqube.yml
+++ b/.github/workflows/sonarqube.yml
@@ -21,6 +21,22 @@ jobs:
         run: |
           sonar-scanner
           
+      - name: Check SonarQube Quality Gate
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # 令牌
+          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}  # 项目密钥
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+        run: |
+          STATUS=$(curl -s -u $SONAR_TOKEN: \\
+            "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY" | \\
+            jq -r .projectStatus.status)
+
+          echo "Quality Gate status: $STATUS"
+
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality gate failed!"
+            exit 1
+          fi
       #- name: SonarQube Scan
       #  env:
       #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # 你可以在 GitHub Secrets 中存储 SonarQube 的token
